nlp_signals:
  model_checkpoint: "FinGPT-Base"  # ProsusAI/finbert or gpt2 or other NLP model
  text_data_path: "data/processed/news_data.csv"
  text_column: "headline"  # Column name in the input data
  buy_threshold: 0.2
  sell_threshold: -0.2
  output_path: "data/interim/nlp_signals.csv"
  batch_size: 16  # Number of samples to process in each batch
  max_length: 512  # Maximum number of tokens in the input sequence

rl_trading:
  agent: "PPO"  # FinRL or DDPG or other RL agent
  env:
    ticker_list: ["AAPL", "MSFT", "GOOG"]
    start_date: "2020-01-01"
    end_date: "2021-01-01"
    time_interval: "1D"  # 1D or 1h or 1m, etc.
  training:
    timesteps: 100000
    learning_rate: 3e-4
    batch_size: 64  # Number of episodes to train the agent
  model_filename: "PPO_model.zip"

execution:
  # Live trading or paper trading config
  enabled: true  # Set to true to enable live trading
  broker: "alpaca"  # alpaca or other broker
  api_key: "YOUR_API_KEY"
  api_secret: "YOUR_API_SECRET"
  paper_trading: true
  base_currency: "USD"  # Not yet implemented
  ticker_list: ["AAPL", "MSFT"]
  model_filename: "PPO_model.zip"
  loop_interval_sec: 60
  initial_cash: 100000.0

  risk_management:
    max_position_size: 100     # shares per trade
    daily_loss_limit: 500.0    # in USD
